# Generated by Django 6.0.5 on 2026-05-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PricingPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=50)),
                ('billing', models.CharField(default='month', max_length=50)),
                ('features_text', models.TextField(help_text='Enter one feature per line')),
                ('is_popular', models.BooleanField(default=False)),
                ('cta_text', models.CharField(default='Get in touch', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anas NC', max_length=100)),
                ('title', models.CharField(default='Graphic Designer', max_length=100)),
                ('hero_title', models.CharField(default="Hey, I'm Anas NC, a Graphic Designer.", max_length=200)),
                ('hero_subtitle', models.TextField(default='Great design should feel invisible. From logo to campaigns, I build brands that connect and convert.')),
                ('about_heading', models.CharField(default='Designer. Strategist. Creative partner.', max_length=200)),
                ('about_subheading', models.CharField(default='Blending clarity and creativity to build brands with purpose.', max_length=200)),
                ('about_bio', models.TextField(default="I'm Anas NC, a freelance brand designer with years of experience helping startups, creators, and growing businesses build identities that feel like them. Blending strategy and style, I'm here to guide you through a fun, collaborative design process.")),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('behind_title', models.CharField(default='Shaping Experiences That Make Life Simpler', max_length=200)),
                ('behind_text', models.TextField(default="I'm a product designer focused on building clean, intuitive interfaces that solve real-world problems.")),
                ('email', models.EmailField(default='hello@anasnc.com', max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(default='India', max_length=100)),
                ('resume', models.FileField(blank=True, null=True, upload_to='resume/')),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('behance', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('dribbble', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='projects/')),
                ('url', models.URLField(blank=True, help_text='External link to project page', null=True)),
                ('is_featured', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0, help_text='Lower values come first')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(blank=True, help_text='Icon class name or SVG identifier', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(help_text='e.g., +01, +02', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('percentage', models.IntegerField(default=90, help_text='Progress bar percentage')),
            ],
        ),
    ]
